### ISSUE TITLE
Several semi-colons missing

### ISSUE THREAD

**Issue by aerwin** [aerwin/sitespeed-utils#7]
@kakazuo -- Hi, Michael... I should have caught it before, but I noticed on several lines you added that there are no semi-colons. When I bring the files into my editor, I get warnings. 

Could you please address this? (And, also, let's make sure you get linting set up in your editor to be able to catch these things.)

**Comment by kakazuo** [comment]
curiously, which editor do you use? I use sublime, seems there is no this kind of warning.

**Comment by aerwin** [comment]
I also use Sublime... But, I've installed the SublimeLinter plug-in (which is probably what you need to do).

**Comment by kakazuo** [comment]
ok, I will check that after installing SublimeLinter plug-in

**Comment by kakazuo** [comment]
fixed this issue, pls help review @aerwin

**Comment by aerwin** [comment]
Resolved w/ https://github.com/aerwin/sitespeed-utils/pull/10
